
import type { LearningUnit, Resource, VisionCard } from './types';

export const courseInfo = {
  name: "Intervención didáctica pedagógica del trabajo docente",
  teacher: "Jesús Antonio Vásquez Córdova",
  degree: "Licenciatura en Educación Especial",
  semester: "Tercero (3°)",
  totalHours: 108,
  credits: 6.75,
};

export const visionGeneralCards: VisionCard[] = [
  {
    icon: '🎯',
    title: "Propósito General",
    description: "Que las y los estudiantes normalistas reconozcan los elementos teóricos, metodológicos y prácticos de la intervención didáctica en los servicios de educación especial, mediante el diseño de propuestas diversificadas, situadas e inclusivas con la finalidad de desarrollar sus habilidades psicopedagógicas para la construcción de su saber docente y resignificar sus experiencias a través de la narrativa pedagógica."
  },
  {
    icon: '🧠',
    title: "Dominios del Saber",
    description: "Participa activamente en la gestión escolar, realiza procesos de educación inclusiva, hace intervención educativa centrada en el alumno, y propone soluciones a problemas del entorno. Desarrolla un pensamiento reflexivo, crítico y creativo con valores y principios éticos."
  },
  {
    icon: '🎓',
    title: "Perfil de Egreso",
    description: "El egresado contará con formación pedagógica y disciplinar sólida para la educación inclusiva. Producirá saber pedagógico, valorando la investigación y la experiencia para transformar la práctica. Desarrollará pensamiento crítico, actuando con respeto, cooperación y solidaridad."
  }
];

export const learningUnits: LearningUnit[] = [
    {
        id: 1,
        title: "La intervención didáctica como proceso de indagación",
        duration: "5 semanas",
        purpose: "Que el estudiantado comprenda los elementos teóricos, metodológicos y prácticos de la intervención didáctica en los servicios de educación especial a través de la búsqueda de información y de la observación situada en los contextos escolar y de aula para reflexionar y continuar en la construcción del hacer, el saber y el ser docente.",
        content: [
            "La identificación y el conocimiento del contexto escolar para la caracterización de la intervención didáctica.",
            "La observación de la intervención didáctica en los servicios de educación especial.",
            "Las condiciones, los materiales y los momentos que hacen posible la intervención didáctica."
        ],
        sessions: [
            { week: 1, sessionInWeek: 1, day: "L", date: "01-09", content: "Presentar el curso, encuadre y diagnóstico de saberes previos sobre intervención y didáctica.", strategy: ["Inicio: Dinámica rompehielos 'Dos verdades, una mentira'.", "Desarrollo: Presentación del programa, competencias, unidades, evaluación y calendario. Normas de trabajo y orientaciones para Jornadas de Observación. Firma de Carta Compromiso.", "Cierre: Lluvia de ideas: '¿Qué es una intervención didáctica y qué la hace especial?'. Diagnóstico grupal."], resources: ["Proyector", "PC", "Presentación", "Programa del curso"], evaluationStrategy: "Evaluación diagnóstica.", evaluationInstrument: "Guía de observación de participación", value: "0%" },
            { week: 1, sessionInWeek: 2, day: "X", date: "03-09", content: "Diferenciar los conceptos de intervención educativa, intervención didáctica y pedagogía", strategy: ["Inicio: Actividad 'Clasificando conceptos' en equipos.", "Desarrollo: Exposición dialogada del docente sobre distinciones conceptuales y metodológicas.", "Cierre: Elaboración de un Diagrama 'V de Gowin' para contrastar 'Pedagogía' y 'Didáctica'."], resources: ["Tarjetas con casos", "Proyector", "PC", "Video de Negrete T. (2017)"], evaluationStrategy: "Evidencia 1 (Parcial): Avance del escrito reflexivo.", evaluationInstrument: "Lista de cotejo.", value: "0%" },
            { week: 1, sessionInWeek: 3, day: "V", date: "05-09", content: "Analizar los elementos teóricos y prácticos que caracterizan la didáctica en la educación especial.", strategy: ["Inicio: 'Nube de palabras' con Mentimeter.", "Desarrollo: Lectura comentada en 'círculos de lectura' de textos de Salvador Mata, Camilloni, Asprelli y Bolívar.", "Cierre: Redacción individual de un párrafo reflexivo en Google Docs sobre desafíos de la didáctica."], resources: ["Lecturas de Salvador, Camilloni, Asprelli, Bolívar", "Acceso a internet (Mentimeter, Google Docs)"], evaluationStrategy: "Evidencia 1 (Parcial): Avance del escrito reflexivo.", evaluationInstrument: "Rúbrica para escrito reflexivo (Criterio de análisis conceptual).", value: "5%" },
            { week: 2, sessionInWeek: 1, day: "L", date: "08-09", content: "Identificar el contexto escolar como punto de partida para la caracterización de la intervención didáctica.", strategy: ["Inicio: Analizar un cortometraje sobre la vida en una escuela.", "Desarrollo: Taller práctico: 'La cartografía de mi escuela'. Diseño de mapa conceptual del contexto escolar.", "Cierre: 'Galería de mapas'. Exposición de cartografías y retroalimentación."], resources: ["Cortometraje", "Proyector", "Papel rotafolio", "Marcadores de colores", "Post-its"], evaluationStrategy: "Coevaluación del trabajo en equipo.", evaluationInstrument: "Lista de cotejo para cartografía conceptual.", value: "0%" },
            { week: 2, sessionInWeek: 2, day: "X", date: "10-09", content: "Diseñar instrumentos de observación cualitativa para recuperar información del contexto y la práctica docente.", strategy: ["Inicio: Juego de roles: Docente vs. Observadores.", "Desarrollo: El docente modela el diseño de una guía de observación y diario de campo. Estudiantes diseñan sus propios instrumentos.", "Cierre: Puesta en común y retroalimentación de los instrumentos diseñados."], resources: ["Textos de Álvarez-Gayou (2004) y Latorre (2004)", "Plantillas de instrumentos", "PC"], evaluationStrategy: "Diseño y/o ajuste de instrumentos.", evaluationInstrument: "Lista de cotejo para el diseño de instrumentos de observación", value: "5%" },
            { week: 2, sessionInWeek: 3, day: "V", date: "12-09", content: "Comprender la narrativa pedagógica como herramienta para la reflexión y la construcción del saber docente.", strategy: ["Inicio: Escuchar un fragmento de un podcast de un docente narrando una experiencia.", "Desarrollo: Análisis del texto de Suárez, D. (2007). Construcción de mapa mental sobre narrativa pedagógica.", "Cierre: Actividad 'El inicio de mi historia'. Escribir el primer párrafo de su propia narrativa pedagógica."], resources: ["Podcast", "Texto de Suárez, D. (2007)", "Proyector", "Pizarra o Jamboard"], evaluationStrategy: "Participación y escritura reflexiva.", evaluationInstrument: "Guía de observación", value: "0%" },
            { week: 3, sessionInWeek: 1, day: "L", date: "15-09", content: "Preparar los detalles de la 1ª Jornada de Prácticas, definiendo focos de observación y logística.", strategy: ["Inicio: Ronda rápida de preguntas sobre emociones/preocupaciones de la jornada.", "Desarrollo: Sesión de taller para afinar instrumentos, elaborar cronograma y redactar carta de presentación.", "Cierre: Simulación (role-playing) de la presentación con el docente titular."], resources: ["Instrumentos diseñados", "Formatos de cronograma y carta", "Computadora"], evaluationStrategy: "Planificación de la jornada.", evaluationInstrument: "Rúbrica de la carpeta de observación.", value: "5%" },
            { week: 3, sessionInWeek: 2, day: "X", date: "17-09", content: "Analizar las condiciones, materiales y momentos que posibilitan la intervención didáctica en preescolar.", strategy: ["Inicio: 'Mercado de ideas'. Recorrer estaciones con imágenes de ambientes de aprendizaje.", "Desarrollo: Debate basado en las variables metodológicas de Zabala (1999).", "Cierre: En su diario de campo, responder sobre aspectos clave a observar en la jornada."], resources: ["Imágenes de aulas", "Texto de Zabala (1999)", "Post-its"], evaluationStrategy: "Participación y análisis.", evaluationInstrument: "Guía de observación de participación.", value: "0%" },
            { week: 3, sessionInWeek: 3, day: "V", date: "19-09", content: "Consolidar la carpeta de observación y resolver dudas finales antes de la jornada de prácticas.", strategy: ["Inicio: Breve meditación guiada.", "Desarrollo: Taller de revisión por pares de las carpetas de observación.", "Cierre: Sesión plenaria de preguntas y respuestas. Entrega de Cartas de Autorización."], resources: ["Carpetas de observación de los estudiantes", "Listas de cotejo para coevaluación"], evaluationStrategy: "Entrega de carpeta de observación.", evaluationInstrument: "Lista de cotejo final de la carpeta.", value: "0%" },
            { week: 4, sessionInWeek: 1, day: "L-V", date: "22-09 al 26-09", content: "Jornada de Observación", strategy: ["Actividad Asíncrona: Foro en Google Classroom 'Diario de Media Semana' para compartir hallazgos, desafíos y preguntas.", "Actividad Sincrónica Opcional: Sesión en Google Meet para resolver dudas urgentes."], resources: ["Google Classroom", "Google Meet"], evaluationStrategy: "Participación en el foro.", evaluationInstrument: "Rúbrica de participación en foro en línea.", value: "0%" },
            { week: 5, sessionInWeek: 1, day: "L", date: "29-09", content: "Socializar y analizar las experiencias y la información recabada durante la jornada de observación.", strategy: ["Inicio: Dinámica 'Círculo de voces' para compartir la anécdota más significativa.", "Desarrollo: En equipos, sistematizan la información en un organizador gráfico (Padlet).", "Cierre: Exposición de los Padlets y se destacan patrones y similitudes."], resources: ["Diarios de campo", "Instrumentos de observación", "Acceso a Padlet"], evaluationStrategy: "Evidencia 2: Información recabada y sistematizada.", evaluationInstrument: "Rúbrica para la sistematización de la información.", value: "15%" },
            { week: 5, sessionInWeek: 2, day: "X", date: "01-10", content: "Redactar el escrito reflexivo final de la Unidad 1, integrando la teoría con la experiencia práctica.", strategy: ["Inicio: Visualización de nubes de palabras y Jamboards de sesiones anteriores.", "Desarrollo: Taller de escritura. Redacción de escrito reflexivo contrastando conceptos teóricos con la práctica observada. Asesoría individualizada.", "Cierre: Comparten en parejas un párrafo de su escrito y reciben retroalimentación."], resources: ["Notas de clase", "Apuntes de lecturas", "Registros de observación", "Computadoras"], evaluationStrategy: "Evidencia 1 (Final): Entrega de escrito reflexivo.", evaluationInstrument: "Rúbrica para escrito reflexivo (argumentación, contraste teoría-práctica, redacción).", value: "20%" }
        ]
    },
    {
        id: 2,
        title: "Intervención didáctica y sistematización del trabajo docente",
        duration: "14 semanas",
        purpose: "Que las y los estudiantes normalistas, desarrollen propuestas diversificadas de intervención didáctica contextualizadas; mediante el diseño de propuestas diversificadas de enseñanza y enfoques globalizadores, a fin de iniciarse en la investigación sobre su propia práctica docente y así establecer rutas que le permitan mejorarla gradualmente.",
        content: [
            "Intervención didáctica en los servicios de educación especial.",
            "Análisis y reflexión de la práctica docente"
        ],
        sessions: [
            { week: 5, sessionInWeek: 3, day: "V", date: "03-10", content: "Analizar los principios de la intervención didáctica en los servicios de educación especial.", strategy: ["Inicio: Actividad 'Receta para aprender'.", "Desarrollo: Debate sobre la lectura de Salvador (1999) contrastando con las 'recetas' iniciales.", "Cierre: Creación de un decálogo del 'Docente de Educación Especial Interventor'."], resources: ["Papel rotafolio", "Marcadores", "Texto de Salvador, F. (1999)"], evaluationStrategy: "Evidencia 3 (Parcial): Inicio de Organizador Gráfico.", evaluationInstrument: "Guía de observación de participación.", value: "5%" },
            { week: 6, sessionInWeek: 1, day: "L", date: "06-10", content: "Identificar distintas metodologías de enseñanza con enfoques globalizadores aplicables a preescolar.", strategy: ["Inicio: Juego de imágenes de aulas trabajando por proyectos, centros de interés y talleres.", "Desarrollo: Actividad 'Mercado de Metodologías'. Exploración en estaciones rotativas.", "Cierre: Puesta en común sobre la metodología más interesante para aplicar."], resources: ["Texto de Zabala, A. (2000)", "Imágenes", "Materiales para estaciones", "Computadora", "Proyector"], evaluationStrategy: "Participación activa.", evaluationInstrument: "Escala estimativa para trabajo en estaciones.", value: "0%" },
            { week: 6, sessionInWeek: 2, day: "X", date: "08-10", content: "Profundizar en el enfoque globalizador y su importancia en el Plan de Estudios 2022.", strategy: ["Inicio: Visualizar fragmento del video de Carro Navarro (2022).", "Desarrollo: Mesa redonda de discusión sobre la importancia del enfoque globalizador y su vinculación con los ejes articuladores.", "Cierre: Creación de un cuadro de múltiple entrada relacionando metodologías y ejes articuladores."], resources: ["Video de Carro Navarro, A. (2022)", "Plan de Estudios 2022", "Computadora", "Proyector"], evaluationStrategy: "Análisis y vinculación curricular.", evaluationInstrument: "Rúbrica para cuadro de múltiple entrada.", value: "0%" },
            { week: 6, sessionInWeek: 3, day: "V", date: "10-10", content: "Analizar los elementos para el diseño de propuestas de intervención educativa (proyectos).", strategy: ["Inicio: 'Lluvia de problemas'.", "Desarrollo: Taller basado en Barraza (2010) para analizar la estructura de un proyecto de intervención.", "Cierre: Cada equipo presenta la idea de su proyecto en 1 minuto."], resources: ["Lectura de Barraza, A. (2010)", "Papel rotafolio", "Marcadores"], evaluationStrategy: "Esbozo de proyecto.", evaluationInstrument: "Lista de cotejo para estructura de proyecto.", value: "0%" },
            { week: 7, sessionInWeek: 1, day: "L", date: "13-10", content: "Introducir el formato de planeación didáctica y sus componentes para la 2ª jornada de intervención.", strategy: ["Inicio: Comparación de 2 ejemplos de planeación (tradicional vs. globalizador).", "Desarrollo: El docente presenta y modela el llenado del formato de planeación. Estudiantes comienzan a vaciar ideas de su proyecto.", "Cierre: Sesión de preguntas y respuestas sobre el llenado del formato."], resources: ["Ejemplos de planeaciones", "Formato oficial de planeación", "PC", "Proyector"], evaluationStrategy: "Comprensión del formato.", evaluationInstrument: "Guía de observación", value: "0%" },
            { week: 7, sessionInWeek: 2, day: "X", date: "15-10", content: "Diseñar la secuencia de actividades de la propuesta de intervención (planeación didáctica).", strategy: ["Inicio: Dinámica 'El hilo conductor'.", "Desarrollo: Taller de diseño de planeación. Desarrollo de secuencia completa de actividades.", "Cierre: Revisión cruzada en parejas, enfocándose en la coherencia."], resources: ["Formato de planeación", "Plan de estudios de Educación Básica 2022", "Computadora"], evaluationStrategy: "Evidencia 4 (Parcial): Borrador de la propuesta de intervención.", evaluationInstrument: "Lista de cotejo para planeación didáctica.", value: "5%" },
            { week: 7, sessionInWeek: 3, day: "V", date: "17-10", content: "Elaborar materiales didácticos innovadores y pertinentes para la propuesta de intervención diseñada.", strategy: ["Inicio: El docente muestra 3 materiales didácticos (tecnológico, reciclado, manipulativo).", "Desarrollo: 'Fábrica de Materiales'. Elaboración de un recurso didáctico clave.", "Cierre: Exposición de los materiales creados."], resources: ["Cartulina, Foami, Tijeras, Pegamento", "Material reciclado", "iPads con apps educativas, etc."], evaluationStrategy: "Creación de material.", evaluationInstrument: "Rúbrica para evaluar material didáctico.", value: "5%" },
            { week: 8, sessionInWeek: 1, day: "L", date: "20-10", content: "Definir estrategias e instrumentos de evaluación formativa para la propuesta de intervención.", strategy: ["Inicio: Debate rápido sobre la evaluación en preescolar.", "Desarrollo: Taller '¿Cómo sé que están aprendiendo?'. Diseño de instrumentos de evaluación formativa.", "Cierre: Coevaluación de los instrumentos diseñados."], resources: ["Planeaciones de los estudiantes", "Ejemplos de instrumentos de evaluación", "PC"], evaluationStrategy: "Diseño de instrumentos.", evaluationInstrument: "Lista de cotejo para instrumentos de evaluación formativa.", value: "0%" },
            { week: 8, sessionInWeek: 2, day: "X", date: "22-10", content: "Recibir retroalimentación final sobre las planeaciones y materiales antes de la 2da Jornada.", strategy: ["Inicio: Ronda de 'semáforo' sobre nivel de preparación y confianza.", "Desarrollo: 'Clínica de planeaciones'. Sesión de asesorías personalizadas.", "Cierre: Plenaria para compartir 'ajustes de último minuto'."], resources: ["Planeaciones impresas", "Materiales didácticos", "Computadora"], evaluationStrategy: "Evidencia 4 (Final): Propuesta de intervención y planificaciones", evaluationInstrument: "Rúbrica de la Propuesta de Intervención (Planeación y materiales).", value: "15%" },
            { week: 8, sessionInWeek: 3, day: "V", date: "24-10", content: "Preparar la logística final de la 2ª jornada y abordar la gestión de imprevistos en el aula.", strategy: ["Inicio: Dinámica de escenarios '¿Qué harías si...?'.", "Desarrollo: Creación de un 'Plan B' para la planeación.", "Cierre: Mensaje motivacional y ronda final de confianza."], resources: ["Planeaciones de los estudiantes", "Tarjetas con escenarios", "Computadora", "Proyector"], evaluationStrategy: "Planificación de contingencias.", evaluationInstrument: "Guía de observación de participación.", value: "0%" },
            { week: 9, sessionInWeek: 1, day: "L-V", date: "27-10 al 31-10", content: "Jornada de Intervención Docente en Jardines de Niños", strategy: ["Actividad asincrónica: Publicar en Google Slides una foto, un resumen y un 'SOS' (duda/problema).", "Actividad sincrónica: Sesión en Google Meet para discutir los 'SOS' en grupo y proponer soluciones."], resources: ["Google Classroom", "Google Slides", "Google Meet"], evaluationStrategy: "Reporte de seguimiento.", evaluationInstrument: "Escala estimativa de la participación y reflexión.", value: "0%" },
            { week: 10, sessionInWeek: 1, day: "L", date: "03-11", content: "Socializar las experiencias de la 2ª jornada de intervención, enfocándose en logros y dificultades.", strategy: ["Inicio: Dinámica 'La maleta del viaje'. Compartir un aprendizaje y una dificultad.", "Desarrollo: En equipos, elaboran una línea de tiempo interactiva (Canva/Genially) de su semana de intervención.", "Cierre: Presentación de las líneas de tiempo, buscando puntos en común."], resources: ["Acceso a Canva/Genially", "PC", "Proyector", "Registros de la práctica"], evaluationStrategy: "Socialización de la experiencia.", evaluationInstrument: "Rúbrica para línea de tiempo.", value: "0%" },
            { week: 10, sessionInWeek: 2, day: "X", date: "05-11", content: "Reflexionar sobre la propia práctica docente a partir de la experiencia de intervención.", strategy: ["Inicio: Lectura en voz alta de un fragmento de Perrenoud.", "Desarrollo: Taller de reflexión guiada a partir de preguntas del programa. Escritura en bitácora.", "Cierre: Comparten en plenaria una de sus reflexiones."], resources: ["Texto de Philippe Perrenoud", "Bitácoras de los estudiantes", "Programa del curso"], evaluationStrategy: "Reflexión escrita.", evaluationInstrument: "Guía de observación de la profundidad de la reflexión.", value: "0%" },
            { week: 10, sessionInWeek: 3, day: "V", date: "07-11", content: "Comprender la sistematización de experiencias como metodología para la reflexión crítica de la práctica.", strategy: ["Inicio: Comentario en parejas: ¿Qué es más útil, contar o analizar lo que pasó?", "Desarrollo: Estudio del texto de Jara (2018) con la técnica de 'rompecabezas'.", "Cierre: Formulación individual de la pregunta inicial que guiará la sistematización."], resources: ["Texto de Jara O. (2018)", "Papel rotafolio", "Marcadores"], evaluationStrategy: "Participación y análisis.", evaluationInstrument: "Guía de preguntas sobre la lectura.", value: "0%" },
            { week: 11, sessionInWeek: 1, day: "L", date: "10-11", content: "Aplicar la metodología de sistematización de experiencias a la práctica docente realizada.", strategy: ["Inicio: Retomar las preguntas eje de la sesión anterior.", "Desarrollo: Taller práctico para sistematizar la 2a jornada siguiendo los pasos de Jara.", "Cierre: Puesta en común de los primeros avances y resolución de dudas."], resources: ["Apuntes sobre Jara (2018)", "Registros de la práctica (planeaciones, diarios, fotos)", "PC"], evaluationStrategy: "Inicio de la sistematización.", evaluationInstrument: "Lista de cotejo del proceso de sistematización", value: "0%" },
            { week: 11, sessionInWeek: 2, day: "X", date: "12-11", content: "Profundizar en la fase de 'reflexión de fondo' de la sistematización: ¿Por qué pasó lo que pasó?", strategy: ["Inicio: Actividad 'Los 5 porqués' para llegar a la causa raíz de un hecho.", "Desarrollo: Los equipos trabajan en la fase de reflexión de fondo, analizando críticamente su experiencia.", "Cierre: Cada equipo comparte una 'conclusión preliminar'."], resources: ["Sistematización en proceso", "Notas de clase", "Textos del curso"], evaluationStrategy: "Análisis crítico de la práctica.", evaluationInstrument: "Rúbrica para la reflexión de fondo.", value: "5%" },
            { week: 11, sessionInWeek: 3, day: "V", date: "14-11", content: "Analizar las narrativas autobiográficas como dispositivos de formación e investigación.", strategy: ["Inicio: Ver el video de Danise Grangeiro. Discusión inicial.", "Desarrollo: Lectura y análisis del texto de Fernando Gil Cantero (1997). Debate sobre la narrativa autobiográfica.", "Cierre: En su bitácora, escriben una breve reflexión sobre su percepción del uso de narrativas autobiográficas."], resources: ["Ejemplos de planeaciones", "Formato oficial de planeación", "PC", "Video de Grangeiro, D. (2021)", "Texto de Gil Cantero, F. (1997)", "Programa del curso"], evaluationStrategy: "Evidencia 5 (Parcial): Inicio de la narrativa pedagógica.", evaluationInstrument: "Guía de observación", value: "0%" },
            { week: 12, sessionInWeek: 1, day: "L", date: "17-11", content: "Suspensión de labores oficial", strategy: [], resources: [], evaluationStrategy: "", evaluationInstrument: "", value: "0%" },
            { week: 12, sessionInWeek: 2, day: "X", date: "19-11", content: "Preparar la 3ª jornada de intervención a partir de la reflexión y sistematización de la práctica anterior.", strategy: ["Inicio: Cada equipo presenta en 2 minutos el principal aprendizaje de su sistematización.", "Desarrollo: Taller de 'Re-planeación'. Diseño de una nueva micro-intervención.", "Cierre: Comparten en parejas los cambios a su forma de planear y por qué."], resources: ["Conclusiones de la sistematización", "Formato de planeación", "PC"], evaluationStrategy: "Diseño de intervención reflexiva.", evaluationInstrument: "Rúbrica para la justificación de la planeación.", value: "0%" },
            { week: 12, sessionInWeek: 3, day: "V", date: "21-11", content: "Taller de diseño de materiales y ajustes razonables para la 3ª jornada de intervención.", strategy: ["Inicio: Lluvia de ideas sobre 'ajustes razonables'.", "Desarrollo: Sesión de taller práctico para trabajar en planeaciones y materiales para la 3ª jornada.", "Cierre: 'Carrusel de retroalimentación' para ver propuestas y dejar comentarios."], resources: ["Planeaciones", "Materiales diversos", "Post-its"], evaluationStrategy: "Refinamiento de la propuesta de intervención", evaluationInstrument: "Coevaluación con lista de cotejo.", value: "0%" },
            { week: 13, sessionInWeek: 1, day: "L", date: "24-11", content: "Introducir la evidencia integradora del curso: El Podcast de mi Trayecto Formativo", strategy: ["Inicio: Escucha de un podcast educativo corto para analizar sus elementos.", "Desarrollo: Presentación detallada de la evidencia integradora (Podcast), sus criterios y estructura.", "Cierre: Lluvia de ideas para posibles temas y títulos de podcasts."], resources: ["Ejemplo de podcast", "Proyector", "Programa del curso"], evaluationStrategy: "Comprensión de la evidencia final.", evaluationInstrument: "Guía de preguntas sobre la tarea.", value: "0%" },
            { week: 13, sessionInWeek: 2, day: "L", date: "26-11", content: "Taller de escritura del guion para el podcast a partir de la narrativa autobiográfica.", strategy: ["Inicio: Ejercicio de escritura creativa 'La anécdota que me marcó'.", "Desarrollo: Taller de guionismo. Se trabaja en la estructura del guion.", "Cierre: Lectura en voz alta de fragmentos de los guiones para recibir retroalimentación."], resources: ["Registros de la práctica", "Bitácoras", "PC", "Plantillas de guion"], evaluationStrategy: "Elaboración del guion del podcast.", evaluationInstrument: "Lista de cotejo para estructura de guion.", value: "0%" },
            { week: 13, sessionInWeek: 3, day: "L", date: "28-11", content: "Revisión final y preparativos para la 3ª jornada de intervención.", strategy: ["Inicio: Autoevaluación rápida sobre preparación para la jornada.", "Desarrollo: Última 'Clínica de planeaciones' y materiales. Presentación de propuestas finales.", "Cierre: Cierre motivacional y logístico para la última jornada."], resources: ["Planeaciones y materiales finales."], evaluationStrategy: "Propuesta de intervención finalizada.", evaluationInstrument: "Rúbrica de la propuesta de intervención", value: "0%" },
            { week: 14, sessionInWeek: 1, day: "L", date: "01-12", content: "Consolidar la narrativa pedagógica como insumo principal para el podcast.", strategy: ["Inicio: 'Galería de Sentimientos'. Escribir en post-its una palabra que resuma su sentir.", "Desarrollo: Taller de escritura para pulir y enriquecer la narrativa pedagógica.", "Cierre: Plenaria para compartir los hilos conductores encontrados en sus trayectorias."], resources: ["Bitácoras", "PC", "Borradores de la narrativa"], evaluationStrategy: "Avance de la narrativa.", evaluationInstrument: "Guía de observación", value: "0%" },
            { week: 14, sessionInWeek: 2, day: "X", date: "03-12", content: "Presentación del organizador gráfico/infografía final de la Unidad 2.", strategy: ["Inicio: Repaso rápido de los temas de la Unidad 2.", "Desarrollo: 'Expo-Ciencia Pedagógica'. Presentación de organizadores gráficos.", "Cierre: Coevaluación y retroalimentación de las presentaciones."], resources: ["Organizadores gráficos/infografías terminados (digitales o físicos)."], evaluationStrategy: "Evidencia 3 (Final): Organizador Gráfico / Infografía.", evaluationInstrument: "Rúbrica para organizador gráfico y su exposición.", value: "10%" },
            { week: 14, sessionInWeek: 3, day: "V", date: "05-12", content: "Suspensión de labores oficial", strategy: [], resources: [], evaluationStrategy: "", evaluationInstrument: "", value: "0%" },
            { week: 15, sessionInWeek: 1, day: "L-V", date: "08-12 al 12-12", content: "Jornada de Intervención Docente en Jardines de Niños", strategy: ["Actividad asíncrona: Usando Flipgrid, grabar un video corto compartiendo un logro y una dificultad.", "Actividad sincrónica: Sesión final de acompañamiento en Google Meet para el cierre de la práctica."], resources: ["Planeaciones de los estudiantes", "Ejemplos de instrumentos de evaluación", "PC"], evaluationStrategy: "Diseño de instrumentos.", evaluationInstrument: "Lista de cotejo para instrumentos de evaluación formativa.", value: "0%" },
            { week: 16, sessionInWeek: 1, day: "L", date: "15-12", content: "Socializar las experiencias de la 3ª jornada de intervención, iniciando el proceso de construcción de la narrativa pedagógica.", strategy: ["Inicio: Dinámica 'El objeto que cuenta mi historia'.", "Desarrollo: Taller 'Cartografía de mi intervención'. Dibujar un mapa del aula y ubicar 3 'hitos narrativos'.", "Cierre: 'Galería de Cartografías'. Exposición de mapas."], resources: ["Papel rotafolio", "Marcadores de colores", "Post-its", "Bitácoras de práctica"], evaluationStrategy: "Socialización y sistematización inicial de la experiencia.", evaluationInstrument: "Guía de observación de la participación y la capacidad de relatar.", value: "0%" },
            { week: 16, sessionInWeek: 2, day: "X", date: "17-12", content: "Profundizar en la reflexión de la práctica a través del análisis de las narrativas, conectando las anécdotas con la teoría.", strategy: ["Inicio: Retomar las cartografías y elegir un hito narrativo.", "Desarrollo: 'Buceo Narrativo'. Ejercicio de escritura reflexiva guiado por preguntas.", "Cierre: En parejas, comparten sus reflexiones."], resources: ["Bitácoras o diarios de campo", "Cartografías de la sesión anterior", "Programa del curso", "PC"], evaluationStrategy: "Reflexión profunda y conexión teoría-práctica.", evaluationInstrument: "Rúbrica para escrito reflexivo corto.", value: "5%" },
            { week: 16, sessionInWeek: 3, day: "V", date: "19-12", content: "Sistematizar la 3ª jornada e integrar todas las experiencias en la narrativa final para el podcast.", strategy: ["Inicio: Dinámica 'Foto-narrativa'.", "Desarrollo: Trabajo final en el guion del podcast.", "Cierre: Presentación del plan de trabajo para enero."], resources: ["Fotos de la práctica", "Guiones del podcast", "PC"], evaluationStrategy: "Evidencia 5 (Final): Narrativa pedagógica (guion final).", evaluationInstrument: "Rúbrica para la estructura y contenido de la narrativa/guion.", value: "10%" },
            { week: 17, sessionInWeek: 1, day: "X", date: "07-01", content: "Taller de producción de podcast: grabación y herramientas de edición de audio.", strategy: ["Periodo Vacacional de Invierno (22/12/2025 al 06/01/2026)", "Inicio: Demostración en vivo de cómo grabar y editar audio.", "Desarrollo: 'Laboratorio de Audio'. Experimentación con grabación y edición.", "Cierre: Comparten primeras pruebas y resuelven dudas."], resources: ["Celulares", "PC con software de edición", "Audífonos", "Tutoriales", "Bancos de música libre"], evaluationStrategy: "Experimentación técnica.", evaluationInstrument: "Lista de cotejo de producción.", value: "0%" },
            { week: 17, sessionInWeek: 2, day: "V", date: "09-01", content: "Taller de grabación y edición del podcast.", strategy: ["Inicio: Ejercicios de calentamiento vocal.", "Desarrollo: Sesión intensiva de grabación y edición.", "Cierre: Establecer fecha límite para entregar borrador del audio."], resources: ["Guiones finais", "PC", "Audífonos", "Micrófonos (opcional)"], evaluationStrategy: "Producción del podcast.", evaluationInstrument: "Guía de observación del trabajo en equipo.", value: "0%" },
            { week: 18, sessionInWeek: 1, day: "L", date: "12-01", content: "Taller de post-producción y revisión por pares de los podcasts.", strategy: ["Inicio: Escucha de un borrador de podcast de un equipo voluntario.", "Desarrollo: Intercambio de archivos de audio y retroalimentación con rúbrica.", "Cierre: Plenaria para compartir sugerencias recurrentes."], resources: ["Archivos de audio", "PC", "Audífonos", "Rúbrica de coevaluación"], evaluationStrategy: "Coevaluación.", evaluationInstrument: "Rúbrica de coevaluación de podcast.", value: "0%" },
            { week: 18, sessionInWeek: 2, day: "X", date: "14-01", content: "Últimos ajustes a la evidencia integradora (Podcast).", strategy: ["Inicio: Ronda de preguntas sobre el mayor reto técnico/creativo.", "Desarrollo: Última sesión de taller para incorporar retroalimentación y ajustes finales.", "Cierre: Instrucciones finales para la entrega y presentación."], resources: ["PC", "Audífonos", "Notas de retroalimentación"], evaluationStrategy: "Finalización de la evidencia.", evaluationInstrument: "Guía de observación", value: "0%" },
            { week: 18, sessionInWeek: 3, day: "V", date: "16-01", content: "Ensayo general y preparación para el Festival de Podcasts.", strategy: ["Inicio: Sorteo del orden de presentación.", "Desarrollo: Cada equipo tiene 5 minutos para prueba de audio e introducción.", "Cierre: Cierre de preparación en ambiente de celebración."], resources: ["Proyector", "Sistema de audio", "PC", "Archivos de audio"], evaluationStrategy: "Preparación de la presentación.", evaluationInstrument: "", value: "0%" }
        ]
    }
];



export const bibliographicResources: Resource[] = [
    { reference: "Álvarez- Gallou, J. L. (2004). Cómo hacer investigación cualitativa.", url: "https://pics.unison.mx/maestria/wp-content/uploads/2020/05/como-hacer-investigacion-cualitativa.pdf" },
    { reference: "Asprelli, M. (2011). La didáctica en la formación docente.", url: "https://archive.org/details/asprelli-m.-la-didactica-en-la-formacion-docente" },
    { reference: "Barraza, A. (2010). Elaboración de propuestas de intervención educativa.", url: "https://upd.edu.mx/PDF/Libros/ElaboracionPropuestas.pdf" },
    { reference: "Bolívar, A. (2008). Didáctica y currículum: de la modernidad a la postmodernidad.", url: "https://portafdcs.wordpress.com/wp-content/uploads/2016/11/didc3a1ctica-y-curriculum-de-la-modernidad-a-la-posmodernidad.pdf" },
    { reference: "Camilloni, A., et al. (2001). Corrientes didácticas contemporáneas.", url: "https://archive.org/details/camilloni-a.-et-al.-corrientes-didacticas-contemporaneas" },
    { reference: "Edelstein, G. (2011). Formar y formarse en la enseñanza.", url: "https://ia600802.us.archive.org/1/items/edelstein-g.-formar-y-formarse-en-la-ensenanza/Edelstein%20G.%20Formar%20y%20formarse%20en%20la%20ensen%CC%83anza_text.pdf" },
    { reference: "Jara O. (2018). La sistematización de experiencias.", url: "https://repository.cinde.org.co/handle/20.500.11907/2121" },
    { reference: "Litwin, E. (2008). El oficio de enseñar: condiciones y contextos.", url: "https://drive.google.com/file/d/0B01w2UytKKSraDNmTEV3RDRvOU0/view?resourcekey=0-6gammsReSv3QDzo1e9flpQ" },
    { reference: "Salvador, F. (1999). Didáctica de la educación especial. Aljibe.", url: "https://es.scribd.com/document/396888237/Didactica-de-la-Educacion-Especial" },
    { reference: "Suárez, D. (2007). Docentes, narrativas e investigación pedagógica en el mundo escolar.", url: "http://www.eemn1tsas.edu.ar/Autoevaluacion/Suarez%20-%20Narrativas%20docentes.pdf" },
    { reference: "Zabala, A. (1999). La práctica educativa, cómo enseñar.", url: "https://archive.org/details/zabala-a.-la-practica-educativa.-como-ensenar" },
];

export const audiovisualResources: Resource[] = [
    { reference: "Negrete, T. (2017) La intervención educativa, distinciones conceptuales y metodológicas.", url: "https://youtu.be/UYcrWP_Q3q4" },
    { reference: "Sanjurjo, L. (2019). El desafío de formar reflexivamente a los profesionales", url: "https://youtu.be/gzpWfFB5j88" },
    { reference: "Dra. Danise Grangeiro, D. (2021). Narrativas autobiográficas como mecanismo de formación", url: "https://www.youtube.com/watch?v=PogzLszSFy4&t=615s" },
];
